#!/usr/bin/env bash

docker run \
  --rm \
  --interactive \
  -t \
  --volume "$(pwd)":/home/work \
  --workdir /home/work \
  --user "$(id -u)":"$(id -g)" \
  --publish "3000:3000" \
  --init \
  c4builder \
  "$@"
